"""add_team_league_name_to_player_stats

Revision ID: 03400ae7cc60
Revises: 1ae0f8115dae
Create Date: 2026-05-30 08:36:51.495847

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03400ae7cc60'
down_revision: Union[str, None] = '1ae0f8115dae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player_stats', sa.Column('team_name', sa.String(length=255), nullable=True, comment='球队名称'))
    op.add_column('player_stats', sa.Column('league_name', sa.String(length=255), nullable=True, comment='联赛名称'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('player_stats', 'league_name')
    op.drop_column('player_stats', 'team_name')
    # ### end Alembic commands ###
