"""make_team_id_nullable_in_player_stats

Revision ID: 1ae0f8115dae
Revises: 7964cc3d3875
Create Date: 2026-05-29 23:32:32.266336

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '1ae0f8115dae'
down_revision: Union[str, None] = '7964cc3d3875'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('player_stats', 'team_id',
               existing_type=mysql.INTEGER(),
               nullable=True,
               existing_comment='球队 ID')
    op.alter_column('player_stats', 'league_id',
               existing_type=mysql.INTEGER(),
               nullable=True,
               existing_comment='联赛 ID')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('player_stats', 'league_id',
               existing_type=mysql.INTEGER(),
               nullable=False,
               existing_comment='联赛 ID')
    op.alter_column('player_stats', 'team_id',
               existing_type=mysql.INTEGER(),
               nullable=False,
               existing_comment='球队 ID')
    # ### end Alembic commands ###
