"""add_league_enabled

Revision ID: 2c9c5fbebfbd
Revises: c8599e8c469b
Create Date: 2026-05-29 22:11:01.164854

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c9c5fbebfbd'
down_revision: Union[str, None] = 'c8599e8c469b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leagues', sa.Column('enabled', sa.Boolean(), nullable=True, comment='是否启用（白名单）'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leagues', 'enabled')
    # ### end Alembic commands ###
