"""add_standings

Revision ID: 5fa77c6875be
Revises: d8aea5d67d80
Create Date: 2026-05-30 09:01:12.873436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5fa77c6875be'
down_revision: Union[str, None] = 'd8aea5d67d80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('standings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='自增 ID'),
    sa.Column('league_id', sa.Integer(), nullable=False, comment='联赛 ID'),
    sa.Column('season', sa.Integer(), nullable=False, comment='赛季年份'),
    sa.Column('group_name', sa.String(length=100), nullable=True, comment='分组名称 (如小组赛/开幕/闭幕)'),
    sa.Column('rank', sa.Integer(), nullable=False, comment='排名'),
    sa.Column('team_id', sa.Integer(), nullable=False, comment='球队 ID'),
    sa.Column('team_name', sa.String(length=255), nullable=False, comment='球队名称'),
    sa.Column('team_logo', sa.String(length=500), nullable=True, comment='球队徽标'),
    sa.Column('points', sa.Integer(), nullable=True, comment='积分'),
    sa.Column('goals_diff', sa.Integer(), nullable=True, comment='净胜球'),
    sa.Column('form', sa.String(length=20), nullable=True, comment='近况 (如 WWDLW)'),
    sa.Column('status', sa.String(length=20), nullable=True, comment='状态 (same/up/down)'),
    sa.Column('description', sa.String(length=200), nullable=True, comment='说明 (如晋级/降级)'),
    sa.Column('all_played', sa.Integer(), nullable=True),
    sa.Column('all_win', sa.Integer(), nullable=True),
    sa.Column('all_draw', sa.Integer(), nullable=True),
    sa.Column('all_lose', sa.Integer(), nullable=True),
    sa.Column('all_goals_for', sa.Integer(), nullable=True),
    sa.Column('all_goals_against', sa.Integer(), nullable=True),
    sa.Column('home_played', sa.Integer(), nullable=True),
    sa.Column('home_win', sa.Integer(), nullable=True),
    sa.Column('home_draw', sa.Integer(), nullable=True),
    sa.Column('home_lose', sa.Integer(), nullable=True),
    sa.Column('home_goals_for', sa.Integer(), nullable=True),
    sa.Column('home_goals_against', sa.Integer(), nullable=True),
    sa.Column('away_played', sa.Integer(), nullable=True),
    sa.Column('away_win', sa.Integer(), nullable=True),
    sa.Column('away_draw', sa.Integer(), nullable=True),
    sa.Column('away_lose', sa.Integer(), nullable=True),
    sa.Column('away_goals_for', sa.Integer(), nullable=True),
    sa.Column('away_goals_against', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('standings')
    # ### end Alembic commands ###
