"""init

Revision ID: 74eeae5ca0dd
Revises: 
Create Date: 2026-05-29 20:00:42.813913

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74eeae5ca0dd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leagues',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False, comment='联赛 ID (来自 API)'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='联赛名称'),
    sa.Column('type', sa.String(length=20), nullable=True, comment='类型: League / Cup'),
    sa.Column('logo', sa.String(length=500), nullable=True, comment='联赛徽标 URL'),
    sa.Column('country_name', sa.String(length=100), nullable=True, comment='国家名称'),
    sa.Column('country_code', sa.String(length=10), nullable=True, comment='国家代码'),
    sa.Column('country_flag', sa.String(length=500), nullable=True, comment='国旗 URL'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('seasons',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='自增 ID'),
    sa.Column('league_id', sa.Integer(), nullable=False, comment='联赛 ID'),
    sa.Column('year', sa.Integer(), nullable=False, comment='赛季年份'),
    sa.Column('start_date', sa.Date(), nullable=True, comment='赛季开始日期'),
    sa.Column('end_date', sa.Date(), nullable=True, comment='赛季结束日期'),
    sa.Column('is_current', sa.Boolean(), nullable=True, comment='是否当前赛季'),
    sa.Column('coverage', sa.JSON(), nullable=True, comment='数据覆盖范围'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('seasons')
    op.drop_table('leagues')
    # ### end Alembic commands ###
