"""add_players

Revision ID: 7964cc3d3875
Revises: 2c9c5fbebfbd
Create Date: 2026-05-29 23:29:34.138532

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7964cc3d3875'
down_revision: Union[str, None] = '2c9c5fbebfbd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('players',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False, comment='球员 ID (来自 API)'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='全名'),
    sa.Column('firstname', sa.String(length=100), nullable=True, comment='名'),
    sa.Column('lastname', sa.String(length=100), nullable=True, comment='姓'),
    sa.Column('age', sa.Integer(), nullable=True, comment='年龄'),
    sa.Column('nationality', sa.String(length=100), nullable=True, comment='国籍'),
    sa.Column('height', sa.String(length=20), nullable=True, comment='身高'),
    sa.Column('weight', sa.String(length=20), nullable=True, comment='体重'),
    sa.Column('injured', sa.Boolean(), nullable=True, comment='是否受伤'),
    sa.Column('photo', sa.String(length=500), nullable=True, comment='头像 URL'),
    sa.Column('birth_date', sa.Date(), nullable=True, comment='出生日期'),
    sa.Column('birth_place', sa.String(length=200), nullable=True, comment='出生地'),
    sa.Column('birth_country', sa.String(length=100), nullable=True, comment='出生国家'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('player_stats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='自增 ID'),
    sa.Column('player_id', sa.Integer(), nullable=False, comment='球员 ID'),
    sa.Column('team_id', sa.Integer(), nullable=False, comment='球队 ID'),
    sa.Column('league_id', sa.Integer(), nullable=False, comment='联赛 ID'),
    sa.Column('season', sa.Integer(), nullable=False, comment='赛季年份'),
    sa.Column('games', sa.JSON(), nullable=True, comment='出场/首发/分钟/位置/评分/队长'),
    sa.Column('substitutes', sa.JSON(), nullable=True, comment='替补上场/被换下/替补席'),
    sa.Column('shots', sa.JSON(), nullable=True, comment='射门统计'),
    sa.Column('goals', sa.JSON(), nullable=True, comment='进球/失球/助攻/扑救'),
    sa.Column('passes', sa.JSON(), nullable=True, comment='传球/关键传球/准确数'),
    sa.Column('tackles', sa.JSON(), nullable=True, comment='抢断/封堵/拦截'),
    sa.Column('duels', sa.JSON(), nullable=True, comment='对抗统计'),
    sa.Column('dribbles', sa.JSON(), nullable=True, comment='过人统计'),
    sa.Column('fouls', sa.JSON(), nullable=True, comment='犯规/被犯规'),
    sa.Column('cards', sa.JSON(), nullable=True, comment='黄牌/红牌'),
    sa.Column('penalty', sa.JSON(), nullable=True, comment='点球统计'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('player_stats')
    op.drop_table('players')
    # ### end Alembic commands ###
