"""add_orders_table

Revision ID: aa8539407817
Revises: 2e1e3ff28115
Create Date: 2026-06-05 18:34:40.289403

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'aa8539407817'
down_revision: Union[str, None] = '2e1e3ff28115'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户ID'),
    sa.Column('order_no', sa.String(length=32), nullable=False, comment='商户订单号'),
    sa.Column('plan_id', sa.String(length=20), nullable=False, comment='套餐: month/quarter/year'),
    sa.Column('amount', sa.DECIMAL(precision=10, scale=2), nullable=False, comment='实付金额'),
    sa.Column('vip_days', sa.Integer(), nullable=False, comment='VIP天数'),
    sa.Column('status', sa.String(length=20), nullable=True, comment='pending/paid/cancelled/expired'),
    sa.Column('payment_method', sa.String(length=20), nullable=True, comment='alipay/admin'),
    sa.Column('trade_no', sa.String(length=64), nullable=True, comment='支付宝交易号'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('paid_at', sa.DateTime(), nullable=True, comment='支付时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_no')
    )
    op.create_index(op.f('ix_orders_user_id'), 'orders', ['user_id'], unique=False)
    op.alter_column('fixtures', 'category',
               existing_type=mysql.VARCHAR(length=20),
               comment='分类标签，如 jingzu',
               existing_nullable=True)
    op.alter_column('users', 'phone',
               existing_type=mysql.VARCHAR(length=20),
               comment='手机号',
               existing_nullable=False)
    op.alter_column('users', 'password_hash',
               existing_type=mysql.VARCHAR(length=255),
               comment='密码hash(管理员用)',
               existing_nullable=True)
    op.alter_column('users', 'username',
               existing_type=mysql.VARCHAR(length=100),
               comment='用户名',
               existing_nullable=True)
    op.alter_column('users', 'role',
               existing_type=mysql.VARCHAR(length=20),
               comment='user/vip/admin',
               existing_nullable=True,
               existing_server_default=sa.text("'user'"))
    op.alter_column('users', 'vip_expires_at',
               existing_type=mysql.DATETIME(),
               comment='VIP到期时间',
               existing_nullable=True)
    op.alter_column('users', 'avatar',
               existing_type=mysql.VARCHAR(length=500),
               comment='头像URL',
               existing_nullable=True)
    op.alter_column('users', 'is_active',
               existing_type=mysql.TINYINT(display_width=1),
               comment='是否启用',
               existing_nullable=True,
               existing_server_default=sa.text("'1'"))
    op.alter_column('users', 'created_at',
               existing_type=mysql.DATETIME(),
               comment='创建时间',
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('users', 'updated_at',
               existing_type=mysql.DATETIME(),
               comment='更新时间',
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'updated_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='更新时间',
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.alter_column('users', 'created_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('users', 'is_active',
               existing_type=mysql.TINYINT(display_width=1),
               comment=None,
               existing_comment='是否启用',
               existing_nullable=True,
               existing_server_default=sa.text("'1'"))
    op.alter_column('users', 'avatar',
               existing_type=mysql.VARCHAR(length=500),
               comment=None,
               existing_comment='头像URL',
               existing_nullable=True)
    op.alter_column('users', 'vip_expires_at',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='VIP到期时间',
               existing_nullable=True)
    op.alter_column('users', 'role',
               existing_type=mysql.VARCHAR(length=20),
               comment=None,
               existing_comment='user/vip/admin',
               existing_nullable=True,
               existing_server_default=sa.text("'user'"))
    op.alter_column('users', 'username',
               existing_type=mysql.VARCHAR(length=100),
               comment=None,
               existing_comment='用户名',
               existing_nullable=True)
    op.alter_column('users', 'password_hash',
               existing_type=mysql.VARCHAR(length=255),
               comment=None,
               existing_comment='密码hash(管理员用)',
               existing_nullable=True)
    op.alter_column('users', 'phone',
               existing_type=mysql.VARCHAR(length=20),
               comment=None,
               existing_comment='手机号',
               existing_nullable=False)
    op.alter_column('fixtures', 'category',
               existing_type=mysql.VARCHAR(length=20),
               comment=None,
               existing_comment='分类标签，如 jingzu',
               existing_nullable=True)
    op.create_table('predictions',
    sa.Column('fixture_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('home_name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('away_name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('home_logo', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('away_logo', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('league_name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('match_date', mysql.DATETIME(), nullable=True),
    sa.Column('model_group', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('win_home', mysql.FLOAT(), nullable=True),
    sa.Column('win_draw', mysql.FLOAT(), nullable=True),
    sa.Column('win_away', mysql.FLOAT(), nullable=True),
    sa.Column('over25_prob', mysql.FLOAT(), nullable=True),
    sa.Column('top3_scores', mysql.JSON(), nullable=True),
    sa.Column('lambda_home', mysql.FLOAT(), nullable=True),
    sa.Column('lambda_away', mysql.FLOAT(), nullable=True),
    sa.Column('llm_win', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('actual_home_goals', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('actual_away_goals', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('win_correct', mysql.TINYINT(), autoincrement=False, nullable=True),
    sa.Column('over25_correct', mysql.TINYINT(), autoincrement=False, nullable=True),
    sa.Column('score_in_top3', mysql.TINYINT(), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('handicap', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('llm_brief', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('llm_core_data', mysql.TEXT(), nullable=True),
    sa.Column('llm_deep_report', mysql.TEXT(), nullable=True),
    sa.Column('llm_handicap', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('llm_over_under', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('llm_score', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('handicap_correct', mysql.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('llm_win_pct', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('llm_handicap_num', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('llm_handicap_team', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('llm_handicap_pct', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('llm_ou_line', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('llm_ou_type', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('llm_ou_pct', mysql.VARCHAR(length=10), nullable=True),
    sa.PrimaryKeyConstraint('fixture_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('scheduler_tasks',
    sa.Column('id', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('interval_seconds', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('start_hour', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.Column('is_enabled', mysql.INTEGER(), server_default=sa.text("'1'"), autoincrement=False, nullable=False),
    sa.Column('last_run', mysql.DATETIME(), nullable=True),
    sa.Column('next_run', mysql.DATETIME(), nullable=True),
    sa.Column('is_running', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('scheduler_logs',
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('task_id', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('task_name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('status', mysql.VARCHAR(length=20), server_default=sa.text("'running'"), nullable=False),
    sa.Column('message', mysql.TEXT(), nullable=True),
    sa.Column('started_at', mysql.DATETIME(), nullable=False),
    sa.Column('finished_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_index(op.f('ix_orders_user_id'), table_name='orders')
    op.drop_table('orders')
    # ### end Alembic commands ###
