"""add_fixtures

Revision ID: ba14b44197e8
Revises: 76f99095e473
Create Date: 2026-05-30 10:46:52.332297

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba14b44197e8'
down_revision: Union[str, None] = '76f99095e473'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fixtures',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False, comment='比赛 ID (来自 API)'),
    sa.Column('date', sa.DateTime(), nullable=True, comment='比赛日期时间 (UTC)'),
    sa.Column('timestamp', sa.Integer(), nullable=True, comment='比赛时间戳'),
    sa.Column('timezone', sa.String(length=50), nullable=True, comment='时区'),
    sa.Column('referee', sa.String(length=255), nullable=True, comment='裁判'),
    sa.Column('first_period', sa.Integer(), nullable=True, comment='上半场开始时间戳'),
    sa.Column('second_period', sa.Integer(), nullable=True, comment='下半场开始时间戳'),
    sa.Column('venue_id', sa.Integer(), nullable=True, comment='场馆 ID'),
    sa.Column('venue_name', sa.String(length=255), nullable=True, comment='场馆名称'),
    sa.Column('venue_city', sa.String(length=100), nullable=True, comment='场馆城市'),
    sa.Column('status_short', sa.String(length=10), nullable=True, comment='状态短码 (FT/1H/NS...)'),
    sa.Column('status_long', sa.String(length=50), nullable=True, comment='状态长描述'),
    sa.Column('status_elapsed', sa.Integer(), nullable=True, comment='已进行分钟数'),
    sa.Column('status_extra', sa.Integer(), nullable=True, comment='补时分钟数'),
    sa.Column('league_id', sa.Integer(), nullable=True, comment='联赛 ID'),
    sa.Column('league_name', sa.String(length=255), nullable=True, comment='联赛名称'),
    sa.Column('season', sa.Integer(), nullable=True, comment='赛季年份'),
    sa.Column('round', sa.String(length=100), nullable=True, comment='轮次'),
    sa.Column('home_id', sa.Integer(), nullable=True, comment='主队 ID'),
    sa.Column('home_name', sa.String(length=255), nullable=True, comment='主队名称'),
    sa.Column('home_logo', sa.String(length=500), nullable=True, comment='主队徽标'),
    sa.Column('home_winner', sa.Boolean(), nullable=True, comment='主队是否获胜'),
    sa.Column('away_id', sa.Integer(), nullable=True, comment='客队 ID'),
    sa.Column('away_name', sa.String(length=255), nullable=True, comment='客队名称'),
    sa.Column('away_logo', sa.String(length=500), nullable=True, comment='客队徽标'),
    sa.Column('away_winner', sa.Boolean(), nullable=True, comment='客队是否获胜'),
    sa.Column('goals_home', sa.Integer(), nullable=True, comment='主队进球'),
    sa.Column('goals_away', sa.Integer(), nullable=True, comment='客队进球'),
    sa.Column('halftime_home', sa.Integer(), nullable=True),
    sa.Column('halftime_away', sa.Integer(), nullable=True),
    sa.Column('fulltime_home', sa.Integer(), nullable=True),
    sa.Column('fulltime_away', sa.Integer(), nullable=True),
    sa.Column('extratime_home', sa.Integer(), nullable=True),
    sa.Column('extratime_away', sa.Integer(), nullable=True),
    sa.Column('penalty_home', sa.Integer(), nullable=True),
    sa.Column('penalty_away', sa.Integer(), nullable=True),
    sa.Column('sub_data_synced', sa.Boolean(), nullable=True, comment='子数据(events/lineups/stats/players)是否已同步'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fixture_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='自增 ID'),
    sa.Column('fixture_id', sa.Integer(), nullable=False, comment='比赛 ID'),
    sa.Column('elapsed', sa.Integer(), nullable=True, comment='事件发生分钟'),
    sa.Column('extra', sa.Integer(), nullable=True, comment='补时分钟'),
    sa.Column('type', sa.String(length=20), nullable=True, comment='事件类型: Goal/Card/Subst/Var'),
    sa.Column('detail', sa.String(length=100), nullable=True, comment='事件详情'),
    sa.Column('comments', sa.String(length=500), nullable=True, comment='备注'),
    sa.Column('team_id', sa.Integer(), nullable=True, comment='球队 ID'),
    sa.Column('team_name', sa.String(length=255), nullable=True, comment='球队名称'),
    sa.Column('player_id', sa.Integer(), nullable=True, comment='球员 ID'),
    sa.Column('player_name', sa.String(length=255), nullable=True, comment='球员姓名'),
    sa.Column('assist_id', sa.Integer(), nullable=True, comment='助攻球员 ID'),
    sa.Column('assist_name', sa.String(length=255), nullable=True, comment='助攻球员姓名'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['fixture_id'], ['fixtures.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fixture_lineups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='自增 ID'),
    sa.Column('fixture_id', sa.Integer(), nullable=False, comment='比赛 ID'),
    sa.Column('team_id', sa.Integer(), nullable=True, comment='球队 ID'),
    sa.Column('team_name', sa.String(length=255), nullable=True, comment='球队名称'),
    sa.Column('formation', sa.String(length=20), nullable=True, comment='阵型 (如 4-2-3-1)'),
    sa.Column('player_id', sa.Integer(), nullable=True, comment='球员 ID'),
    sa.Column('player_name', sa.String(length=255), nullable=True, comment='球员姓名'),
    sa.Column('player_number', sa.Integer(), nullable=True, comment='球衣号码'),
    sa.Column('player_position', sa.String(length=20), nullable=True, comment='位置'),
    sa.Column('player_grid', sa.String(length=20), nullable=True, comment='网格坐标'),
    sa.Column('is_substitute', sa.Boolean(), nullable=True, comment='false=首发 true=替补'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['fixture_id'], ['fixtures.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fixture_player_stats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='自增 ID'),
    sa.Column('fixture_id', sa.Integer(), nullable=False, comment='比赛 ID'),
    sa.Column('team_id', sa.Integer(), nullable=True, comment='球队 ID'),
    sa.Column('team_name', sa.String(length=255), nullable=True, comment='球队名称'),
    sa.Column('player_id', sa.Integer(), nullable=True, comment='球员 ID'),
    sa.Column('player_name', sa.String(length=255), nullable=True, comment='球员姓名'),
    sa.Column('player_photo', sa.String(length=500), nullable=True, comment='球员头像'),
    sa.Column('games', sa.JSON(), nullable=True, comment='出场信息'),
    sa.Column('offsides', sa.Integer(), nullable=True, comment='越位'),
    sa.Column('shots', sa.JSON(), nullable=True),
    sa.Column('goals', sa.JSON(), nullable=True),
    sa.Column('passes', sa.JSON(), nullable=True),
    sa.Column('tackles', sa.JSON(), nullable=True),
    sa.Column('duels', sa.JSON(), nullable=True),
    sa.Column('dribbles', sa.JSON(), nullable=True),
    sa.Column('fouls', sa.JSON(), nullable=True),
    sa.Column('cards', sa.JSON(), nullable=True),
    sa.Column('penalty', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['fixture_id'], ['fixtures.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fixture_statistics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='自增 ID'),
    sa.Column('fixture_id', sa.Integer(), nullable=False, comment='比赛 ID'),
    sa.Column('team_id', sa.Integer(), nullable=True, comment='球队 ID'),
    sa.Column('team_name', sa.String(length=255), nullable=True, comment='球队名称'),
    sa.Column('stat_type', sa.String(length=100), nullable=True, comment='统计类型 (如 Shots on Goal)'),
    sa.Column('stat_value', sa.String(length=50), nullable=True, comment='统计值 (可为数字或百分比字符串)'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['fixture_id'], ['fixtures.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fixture_statistics')
    op.drop_table('fixture_player_stats')
    op.drop_table('fixture_lineups')
    op.drop_table('fixture_events')
    op.drop_table('fixtures')
    # ### end Alembic commands ###
