"""add_teams_venues

Revision ID: c8599e8c469b
Revises: 74eeae5ca0dd
Create Date: 2026-05-29 21:03:05.680969

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8599e8c469b'
down_revision: Union[str, None] = '74eeae5ca0dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('venues',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False, comment='场馆 ID (来自 API)'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='场馆名称'),
    sa.Column('address', sa.String(length=500), nullable=True, comment='地址'),
    sa.Column('city', sa.String(length=100), nullable=True, comment='城市'),
    sa.Column('country', sa.String(length=100), nullable=True, comment='国家'),
    sa.Column('capacity', sa.Integer(), nullable=True, comment='容量'),
    sa.Column('surface', sa.String(length=50), nullable=True, comment='场地类型'),
    sa.Column('image', sa.String(length=500), nullable=True, comment='图片 URL'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('teams',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False, comment='球队 ID (来自 API)'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='球队名称'),
    sa.Column('code', sa.String(length=10), nullable=True, comment='球队代码'),
    sa.Column('country', sa.String(length=100), nullable=True, comment='所在国家'),
    sa.Column('founded', sa.Integer(), nullable=True, comment='成立年份'),
    sa.Column('national', sa.Boolean(), nullable=True, comment='是否国家队'),
    sa.Column('logo', sa.String(length=500), nullable=True, comment='徽标 URL'),
    sa.Column('venue_id', sa.Integer(), nullable=True, comment='主场馆 ID'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('teams')
    op.drop_table('venues')
    # ### end Alembic commands ###
