"""drop_team_league_name_from_player_stats

Revision ID: d8aea5d67d80
Revises: 03400ae7cc60
Create Date: 2026-05-30 08:41:32.257275

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'd8aea5d67d80'
down_revision: Union[str, None] = '03400ae7cc60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('player_stats', 'team_name')
    op.drop_column('player_stats', 'league_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player_stats', sa.Column('league_name', mysql.VARCHAR(length=255), nullable=True, comment='联赛名称'))
    op.add_column('player_stats', sa.Column('team_name', mysql.VARCHAR(length=255), nullable=True, comment='球队名称'))
    # ### end Alembic commands ###
